version: '3.8'

services:
  server:
    build: ./server
    container_name: nutrismart-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      # Pass your local .env variables to the container
      - MONGO_URI=${MONGO_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: nutrismart-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Essential for hot-reloading on some systems
      - WDS_SOCKET_PORT=0 # Fixes React polling errors
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true # Needed for React
    tty: true       # Needed for React